---
name: Package Daemon+CLI
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04-riscv
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: |
          git config --global --add safe.directory '*'
          git submodule update --init --depth=1 dist-assets/binaries
      # The container image already has rustup and the pinned version of Rust
      - name: Install Rust toolchain
        # When running this job for "stable" test against our pinned rust version
        # instead of the stable channel.
        if: ${{ matrix.rust != 'stable' }}
        run: rustup override set ${{ matrix.rust }}
      - name: Install dependencies
        run: |
          sudo apt install -y protobuf-compiler gcc libdbus-1-dev rpm
          cargo install cargo-deb cargo-generate-rpm
      - name: Package Daemon + CLI
        run: ./build.sh --daemon-only --optimize
